apiVersion: v1
kind: Service
metadata:
  name: robot-gallery-service
spec:
  type: NodePort
  selector:
    app: robot-gallery
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
